export default [
  {
    files: ["src/**/*.{js,gs}"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        global: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        // Google Apps Script globals
        Logger: "readonly",
        HtmlService: "readonly",
        Session: "readonly",
        SpreadsheetApp: "readonly",
        DriveApp: "readonly",
        PropertiesService: "readonly",
        CacheService: "readonly",
        UrlFetchApp: "readonly",
        Utilities: "readonly",
        ScriptApp: "readonly",
        CalendarApp: "readonly",
        GmailApp: "readonly",
        DocumentApp: "readonly",
        FormApp: "readonly",
        SlidesApp: "readonly",
        Sheets: "readonly",
        BigQuery: "readonly",
        FirebaseApp: "readonly",
        XmlService: "readonly",
        ContentService: "readonly",
        LockService: "readonly",
        AdminDirectory: "readonly",
        GroupsApp: "readonly",
        People: "readonly",
        Tasks: "readonly",
        YouTube: "readonly",
        LanguageApp: "readonly",
        Maps: "readonly",
        Translate: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "off", // Disabled for Google Apps Script - functions called dynamically
      "no-console": "off",
      "no-undef": "off", // Google Apps Script globals
    },
  },
  {
    ignores: ["**/*.test.js", "node_modules/**"],
  },
];
